"""payment simulation tables

Revision ID: 20260822_0002
Revises: 20260822_0001
"""
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = "20260822_0002"; down_revision: str | Sequence[str] | None = "20260822_0001"; branch_labels = None; depends_on = None
payment_status = postgresql.ENUM("created", "pending", "authorized", "captured", "failed", "refunded", "partially_refunded", name="payment_status", create_type=False)
subscription_status = postgresql.ENUM("active", "past_due", "cancelled", name="subscription_status", create_type=False)
link_status = postgresql.ENUM("active", "paid", "expired", "cancelled", name="payment_link_status", create_type=False)
def upgrade() -> None:
    bind = op.get_bind(); payment_status.create(bind, checkfirst=True); subscription_status.create(bind, checkfirst=True); link_status.create(bind, checkfirst=True)
    op.create_table("merchants", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index("ix_merchants_email", "merchants", ["email"])
    op.create_table("customers", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("merchant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("merchants.id"), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("email", sa.String(320), nullable=False), sa.Column("phone", sa.String(32)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("merchant_id", "email", name="uq_customer_merchant_email")); op.create_index("ix_customers_merchant_id", "customers", ["merchant_id"])
    op.create_table("subscriptions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("merchant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("merchants.id"), nullable=False), sa.Column("customer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("customers.id"), nullable=False), sa.Column("plan_name", sa.String(160), nullable=False), sa.Column("amount", sa.Numeric(14,2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", subscription_status, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index("ix_subscriptions_customer_status", "subscriptions", ["customer_id", "status"])
    op.create_table("payments", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("merchant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("merchants.id"), nullable=False), sa.Column("customer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("customers.id"), nullable=False), sa.Column("subscription_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("subscriptions.id")), sa.Column("retry_of_payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id")), sa.Column("idempotency_key", sa.String(128), unique=True), sa.Column("amount", sa.Numeric(14,2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", payment_status, nullable=False), sa.Column("failure_code", sa.String(80)), sa.Column("attempted_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("captured_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index("ix_payments_customer_status", "payments", ["customer_id","status"]); op.create_index("ix_payments_subscription_attempted", "payments", ["subscription_id","attempted_at"])
    op.create_table("refunds", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id"), nullable=False), sa.Column("amount", sa.Numeric(14,2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("idempotency_key", sa.String(128), unique=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index("ix_refunds_payment_created", "refunds", ["payment_id","created_at"])
    op.create_table("payment_links", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("customer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("customers.id"), nullable=False), sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id")), sa.Column("subscription_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("subscriptions.id")), sa.Column("token", sa.String(64), nullable=False, unique=True), sa.Column("amount", sa.Numeric(14,2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", link_status, nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("communications", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("customer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("customers.id"), nullable=False), sa.Column("channel", sa.String(32), nullable=False), sa.Column("body", sa.Text(), nullable=False), sa.Column("idempotency_key", sa.String(128), unique=True), sa.Column("status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
def downgrade() -> None:
    for table in ("communications","payment_links","refunds","payments","subscriptions","customers","merchants"): op.drop_table(table)
    bind=op.get_bind(); link_status.drop(bind, checkfirst=True); subscription_status.drop(bind, checkfirst=True); payment_status.drop(bind, checkfirst=True)
